"use client";
import {useState} from "react";
import {Download,FileSpreadsheet,RefreshCw,ShieldCheck,Upload} from "lucide-react";
export default function Page(){
 const [file,setFile]=useState<File|null>(null); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const [allowDelete,setAllowDelete]=useState(false);
 async function sync(e:React.FormEvent){e.preventDefault();if(!file)return;setBusy(true);setMsg("Menyinkronkan workbook...");const fd=new FormData();fd.append("file",file);fd.append("allowDelete",String(allowDelete));const r=await fetch("/api/excel/sync",{method:"POST",body:fd});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||"Sinkronisasi gagal.");return}setMsg(`Selesai. Anggota dibuat ${d.membersCreated}, diperbarui ${d.membersUpdated}. Pembayaran dibuat ${d.paymentsCreated}, diperbarui ${d.paymentsUpdated}. Pengeluaran dibuat ${d.expensesCreated}, diperbarui ${d.expensesUpdated}. ${d.deleted?`Dihapus ${d.deleted}.`:"Tidak ada data yang dihapus."} ${d.warnings?.length?`Peringatan: ${d.warnings.length}.`:""}`)}
 return <div className="p-6 lg:p-8"><div className="mx-auto max-w-5xl"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Data</p><h1 className="mt-2 text-2xl font-semibold">Sinkronisasi Excel</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Edit workbook di Excel, simpan, lalu unggah dan klik sinkronkan. Kolom Sync ID menjaga baris tetap terhubung ke data website sehingga perubahan nominal, tanggal, nama, dan keterangan dapat memperbarui data yang sama.</p></header>
 <div className="mt-6 grid gap-5 lg:grid-cols-2">
  <section className="border border-line bg-white p-5 shadow-soft"><div className="flex items-center gap-3"><FileSpreadsheet size={19}/><h2 className="font-semibold">1. Ambil workbook sinkronisasi</h2></div><p className="mt-2 text-sm text-slate-500">Selalu mulai dari workbook ini agar setiap baris memiliki Sync ID. Jangan mengubah kolom Sync ID.</p><a href="/api/excel/sync-template" className="mt-5 inline-flex items-center gap-2 bg-ink px-4 py-2.5 text-sm font-semibold text-white"><Download size={16}/>Download workbook</a></section>
  <section className="border border-line bg-white p-5 shadow-soft"><div className="flex items-center gap-3"><Upload size={19}/><h2 className="font-semibold">2. Sinkronkan perubahan</h2></div><form onSubmit={sync} className="mt-4"><input required type="file" accept=".xlsx" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full text-sm"/><label className="mt-4 flex items-start gap-3 border border-line p-3 text-sm"><input type="checkbox" checked={allowDelete} onChange={e=>setAllowDelete(e.target.checked)} className="mt-1"/><span><b>Izinkan penghapusan</b><br/><span className="text-xs text-slate-500">Baris transaksi yang memiliki Sync ID tetapi dihapus dari Excel akan dihapus dari database. Gunakan hanya jika memang ingin mencerminkan penghapusan.</span></span></label><button disabled={!file||busy} className="mt-4 inline-flex w-full items-center justify-center gap-2 bg-ink px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><RefreshCw size={16} className={busy?"animate-spin":""}/>{busy?"Menyinkronkan...":"Sinkronkan ke Website"}</button></form>{msg&&<p className="mt-4 border border-line bg-slate-50 p-3 text-sm text-slate-700">{msg}</p>}</section>
 </div>
 <section className="mt-5 border border-line bg-white p-5"><div className="flex items-center gap-3"><ShieldCheck size={18}/><h2 className="font-semibold">Aturan aman</h2></div><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600"><li>Jangan mengedit kolom Sync ID.</li><li>Jangan mengubah nama sheet utama.</li><li>Untuk perubahan biasa, gunakan workbook hasil download dari website.</li><li>Sinkronisasi dijalankan oleh bendahara yang sudah login.</li><li>Data publik akan membaca database setelah sinkronisasi selesai.</li></ul></section>
 </div></div>
}
